/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.ai.skolafudbala.forme;

import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.ai.skolafudbala.klijent.Klijent;
import rs.ac.bg.fon.ai.skolafudbala.model.Korisnik;
import rs.ac.bg.fon.ai.skolafudbala.nacinprikazaforme.Prikaz;




/**
 *
 * @author Korisnik
 */
public class MainForma extends javax.swing.JFrame {

    Korisnik trenutnoUlogovani;

    /**
     * Creates new form MainForma
     */
    public MainForma(Korisnik k) {
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        popuniLabelu(k);

        this.setTitle("Škola fudbala");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabelZdravo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFudbaler = new javax.swing.JMenu();
        jCheckBoxMenuItemUnosFudbalera = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemPrikazFudbalera = new javax.swing.JCheckBoxMenuItem();
        jMenuTrener = new javax.swing.JMenu();
        jCheckBoxMenuItemUnesiTrenera = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuTreningGrupa = new javax.swing.JMenu();
        jCheckBoxMenuItemUnosTreningGrupe = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItemUnesiTekmu = new javax.swing.JCheckBoxMenuItem();
        LekarskiPregled = new javax.swing.JMenu();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItemPonovo = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemKraj = new javax.swing.JCheckBoxMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelZdravo.setText("jLabel1");

        jLabel1.setText("Odaberite opciju iz glavnog menija!");

        jMenuFudbaler.setText("Fudbaler");

        jCheckBoxMenuItemUnosFudbalera.setSelected(true);
        jCheckBoxMenuItemUnosFudbalera.setText("Unesi fudbalera");
        jCheckBoxMenuItemUnosFudbalera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemUnosFudbaleraActionPerformed(evt);
            }
        });
        jMenuFudbaler.add(jCheckBoxMenuItemUnosFudbalera);

        jCheckBoxMenuItemPrikazFudbalera.setSelected(true);
        jCheckBoxMenuItemPrikazFudbalera.setText("Prikaz fudbalera");
        jCheckBoxMenuItemPrikazFudbalera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemPrikazFudbaleraActionPerformed(evt);
            }
        });
        jMenuFudbaler.add(jCheckBoxMenuItemPrikazFudbalera);

        jMenuBar1.add(jMenuFudbaler);

        jMenuTrener.setText("Trener");

        jCheckBoxMenuItemUnesiTrenera.setSelected(true);
        jCheckBoxMenuItemUnesiTrenera.setText("Unesi trenera");
        jCheckBoxMenuItemUnesiTrenera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemUnesiTreneraActionPerformed(evt);
            }
        });
        jMenuTrener.add(jCheckBoxMenuItemUnesiTrenera);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Prikaz trenera");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenuTrener.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenuTrener);

        jMenuTreningGrupa.setText("Trening grupa");

        jCheckBoxMenuItemUnosTreningGrupe.setSelected(true);
        jCheckBoxMenuItemUnosTreningGrupe.setText("Unesi trening grupu");
        jCheckBoxMenuItemUnosTreningGrupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemUnosTreningGrupeActionPerformed(evt);
            }
        });
        jMenuTreningGrupa.add(jCheckBoxMenuItemUnosTreningGrupe);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Prikaz trening grupa");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenuTreningGrupa.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenuTreningGrupa);

        jMenu4.setText("Trening utakmica");

        jCheckBoxMenuItemUnesiTekmu.setSelected(true);
        jCheckBoxMenuItemUnesiTekmu.setText("Unesi trening utakmicu");
        jCheckBoxMenuItemUnesiTekmu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemUnesiTekmuActionPerformed(evt);
            }
        });
        jMenu4.add(jCheckBoxMenuItemUnesiTekmu);

        jMenuBar1.add(jMenu4);

        LekarskiPregled.setText("Lekarski pregled");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Unesi lekarski pregled");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        LekarskiPregled.add(jCheckBoxMenuItem3);

        jMenuBar1.add(LekarskiPregled);

        jMenu3.setText("Odjava");

        jCheckBoxMenuItemPonovo.setSelected(true);
        jCheckBoxMenuItemPonovo.setText("Odjava i nova prijava");
        jCheckBoxMenuItemPonovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemPonovoActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItemPonovo);

        jCheckBoxMenuItemKraj.setSelected(true);
        jCheckBoxMenuItemKraj.setText("Odjava i zavrsetak rada");
        jCheckBoxMenuItemKraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemKrajActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItemKraj);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelZdravo, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabelZdravo)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItemKrajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemKrajActionPerformed
        try {
            String odjava = Klijent.getInstance().odjava();
            JOptionPane.showMessageDialog(this, odjava, "Odjava", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception ex) {
            if (ex instanceof IOException) {
                JOptionPane.showMessageDialog(this, "Greska! Pokusajte kasnije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            } else {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jCheckBoxMenuItemKrajActionPerformed

    private void jCheckBoxMenuItemPonovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemPonovoActionPerformed
        try {
            String odjava = Klijent.getInstance().odjava();
            this.dispose();
            PrijavaForma pf = new PrijavaForma();
            pf.setVisible(true);
            JOptionPane.showMessageDialog(this, odjava, "Odjava", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            if (ex instanceof IOException) {
                JOptionPane.showMessageDialog(this, "Greska! Pokusajte kasnije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            } else {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jCheckBoxMenuItemPonovoActionPerformed

    private void jCheckBoxMenuItemUnosFudbaleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemUnosFudbaleraActionPerformed
        try {
            UnosIzmjenaFudbaleraForma uff = new UnosIzmjenaFudbaleraForma(Prikaz.DODAJ_FORMA, null);
            uff.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            uff.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska! Server nije pokrenut!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemUnosFudbaleraActionPerformed

    private void jCheckBoxMenuItemUnesiTreneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemUnesiTreneraActionPerformed
        //try {
        UnosIzmjenaTreneraForma utf = new UnosIzmjenaTreneraForma(Prikaz.DODAJ_FORMA, null);
        utf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        utf.setVisible(true);
        //} catch (Exception ex) {
        /*if (ex instanceof IOException) {
                JOptionPane.showMessageDialog(this, "Greska! Pokusajte kasnije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                this.dispose();
            }
            if (ex instanceof NullPointerException) {
                JOptionPane.showMessageDialog(this, "Greska! Server nije pokrenut!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                this.dispose();
            }*/
        //JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        //this.dispose();

    }//GEN-LAST:event_jCheckBoxMenuItemUnesiTreneraActionPerformed

    private void jCheckBoxMenuItemUnosTreningGrupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemUnosTreningGrupeActionPerformed
        UnosIzmjenaTreningGrupeForma utg = new UnosIzmjenaTreningGrupeForma(Prikaz.DODAJ_FORMA, null);
        utg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        utg.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItemUnosTreningGrupeActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        PregledTreneraForma ptf = new PregledTreneraForma();
        ptf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ptf.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItemPrikazFudbaleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemPrikazFudbaleraActionPerformed
        PregledFudbaleraForma pff = new PregledFudbaleraForma();
        pff.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pff.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItemPrikazFudbaleraActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        try {
            PregledTreningGrupaForma ptg = new PregledTreningGrupaForma();
            ptg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            ptg.setVisible(true);
        } catch (Exception ex) {
            if (ex instanceof IOException) {
                this.dispose();
            }
            if (ex instanceof NullPointerException) {
                JOptionPane.showMessageDialog(this, "Greska! Server nije pokrenut!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                this.dispose();
            }
            JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jCheckBoxMenuItemUnesiTekmuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemUnesiTekmuActionPerformed
        UnosTreningUtakmiceForma utuf = new UnosTreningUtakmiceForma(this, rootPaneCheckingEnabled);
        utuf.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItemUnesiTekmuActionPerformed

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
        UnosLekarskogPregledaForma ulp = new UnosLekarskogPregledaForma();
        ulp.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu LekarskiPregled;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemKraj;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemPonovo;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemPrikazFudbalera;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemUnesiTekmu;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemUnesiTrenera;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemUnosFudbalera;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemUnosTreningGrupe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelZdravo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFudbaler;
    private javax.swing.JMenu jMenuTrener;
    private javax.swing.JMenu jMenuTreningGrupa;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables

    private void popuniLabelu(Korisnik k) {
        trenutnoUlogovani = k;
        jLabelZdravo.setText("Zdravo, " + trenutnoUlogovani.getIme() + " " + trenutnoUlogovani.getPrezime() + "!" + " Nadam se da se osjećate lijepo danas.");
    }
}
