/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rs.ac.bg.fon.ai.skolafudbala.forme;

import java.io.IOException;
import rs.ac.bg.fon.ai.skolafudbala.klijent.Klijent;
import rs.ac.bg.fon.ai.skolafudbala.model.Fudbaler;
import rs.ac.bg.fon.ai.skolafudbala.model.Trener;
import rs.ac.bg.fon.ai.skolafudbala.model.TreningGrupa;
import rs.ac.bg.fon.ai.skolafudbala.modelitabele.ModelTabeleFudbalerTG;
import rs.ac.bg.fon.ai.skolafudbala.nacinprikazaforme.Prikaz;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author Korisnik
 */
public class PregledFudbaleraForma extends javax.swing.JFrame {

    Fudbaler fudbaler;
    List<TreningGrupa> listaTreningGrupa = new ArrayList<>();
    ModelTabeleFudbalerTG modelTabeleFudbaler;
    List<Fudbaler> pretrazeniFudbaleri = new ArrayList<>();

    /**
     * Creates new form PregledFudbaleraForma
     */
    public PregledFudbaleraForma() {
        initComponents();
        this.setTitle("Informacije o postojećim fudbalerima");
        try {
            popuniTabeluFudbaler();
        } catch (Exception ex) {
            if (ex instanceof IOException) {
                JOptionPane.showMessageDialog(this, "Greska! Pokusajte kasnije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }
        try {
            popuniComboTreningGrupa();
        } catch (Exception ex) {
            if (ex instanceof IOException) {
                JOptionPane.showMessageDialog(this, "Greska! Pokusajte kasnije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFudbaleri = new javax.swing.JTable();
        jButtonIzmjeni = new javax.swing.JButton();
        jButtonPretrazi = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jTextFieldJmbg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTreningGrupa = new javax.swing.JComboBox<>();
        jButtonPretraziOsvjezi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Fudbaleri");
        jLabel1.setMinimumSize(new java.awt.Dimension(60, 60));

        jLabel2.setText("Ime:");

        jLabel3.setText("JMBG:");

        jTableFudbaleri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableFudbaleri);

        jButtonIzmjeni.setText("Izmjeni");
        jButtonIzmjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmjeniActionPerformed(evt);
            }
        });

        jButtonPretrazi.setText("Pretraži");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("Obriši");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jLabel4.setText("Trening grupa:");

        jButtonPretraziOsvjezi.setText("Osvježi");
        jButtonPretraziOsvjezi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziOsvjeziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonIzmjeni, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPretraziOsvjezi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(jButtonObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxTreningGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jButtonPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretrazi)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxTreningGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIzmjeni)
                    .addComponent(jButtonObrisi)
                    .addComponent(jButtonPretraziOsvjezi))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        try {
            String ime = jTextFieldIme.getText();
            String jmbg = jTextFieldJmbg.getText();
            TreningGrupa tg = (TreningGrupa) jComboBoxTreningGrupa.getSelectedItem();
            if (tg == null) {
                tg = new TreningGrupa(-1, null, -1, new Trener());
            }
            boolean prazno = validirajPrazno(ime, jmbg, tg);
            String validan = validiraj(ime, jmbg);
            if (!prazno) {
                if (validan.equals("")) {
                    Fudbaler fudbalerPretraga = new Fudbaler(ime, null, jmbg, null, tg, null);
                    pretrazeniFudbaleri = Klijent.getInstance().nadjiFudbalere(fudbalerPretraga);
                    if (pretrazeniFudbaleri.size() == 1) {
                        JOptionPane.showMessageDialog(this, "Sistem je pronašao fudbalera po zadatim vrijednostima!", "Pretraga", JOptionPane.INFORMATION_MESSAGE);
                        osvjeziPolja();
                    } else {
                        JOptionPane.showMessageDialog(this, "Sistem je pronašao fudbalere po zadatim vrijednostima!", "Pretraga", JOptionPane.INFORMATION_MESSAGE);
                    }
                    osvjeziTabeluPretraga();

                } else {
                    JOptionPane.showMessageDialog(this, "Neispravan format: " + validan, "GRESKA", JOptionPane.ERROR_MESSAGE);
                    jComboBoxTreningGrupa.setSelectedIndex(-1);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Morate da unesete bar jedno polje da biste izvršili pretragu!", "GRESKA", JOptionPane.ERROR_MESSAGE);

            }

        } catch (Exception ex) {
            if (ex instanceof IOException) {
                JOptionPane.showMessageDialog(this, "Greska! Pokusajte kasnije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            } else {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
                jComboBoxTreningGrupa.setSelectedIndex(-1);
                if (pretrazeniFudbaleri.size() > 0) {
                    modelTabeleFudbaler = new ModelTabeleFudbalerTG(pretrazeniFudbaleri);
                    jTableFudbaleri.setModel(modelTabeleFudbaler);
                }
                try {
                    modelTabeleFudbaler = new ModelTabeleFudbalerTG();
                } catch (Exception ex1) {
                    if (ex instanceof IOException) {
                        JOptionPane.showMessageDialog(this, "Greska! Pokusajte kasnije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                        System.exit(0);
                    }
                }

                jTableFudbaleri.setModel(modelTabeleFudbaler);
                osvjeziPolja();
            }

        }
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonIzmjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmjeniActionPerformed
        if (jTableFudbaleri.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita fudbalera! Morate selektovati bar jednog fudbalera!", "GRESKA", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Fudbaler fudbaler = modelTabeleFudbaler.get(jTableFudbaleri.getSelectedRow());
                Fudbaler fudbalerBaza = Klijent.getInstance().ucitajFudbalera(fudbaler);

                JOptionPane.showMessageDialog(this, "Sistem je učitao fudbalera!", "Fudbaler učitan", JOptionPane.INFORMATION_MESSAGE);
                UnosIzmjenaFudbaleraForma utf = new UnosIzmjenaFudbaleraForma(this, Prikaz.IZMJENI_FORMA, fudbalerBaza);
                utf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                utf.setVisible(true);
            } catch (Exception ex) {
                if (ex instanceof IOException) {
                    JOptionPane.showMessageDialog(this, "Greska! Pokusajte kasnije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                } else {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_jButtonIzmjeniActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        if (jTableFudbaleri.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita fudbalere! Morate selektovati bar jednog fudbalera!", "GRESKA", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                fudbaler = modelTabeleFudbaler.get(jTableFudbaleri.getSelectedRow());
                Fudbaler fudbalerBaza = Klijent.getInstance().ucitajFudbalera(fudbaler);
                UnosIzmjenaFudbaleraForma uif = new UnosIzmjenaFudbaleraForma(this, Prikaz.OBRISI_FORMA, fudbalerBaza);
                uif.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                JOptionPane.showMessageDialog(this, "Sistem je učitao fudbalera!", "Fudbaler učitan", JOptionPane.INFORMATION_MESSAGE);
                uif.setVisible(true);

            } catch (Exception ex) {
                if (ex instanceof IOException) {
                    JOptionPane.showMessageDialog(this, "Greska! Pokusajte kasnije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                } else {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonPretraziOsvjeziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziOsvjeziActionPerformed
        try {
            popuniTabeluFudbaler();
        } catch (Exception ex) {
            if (ex instanceof IOException) {
                JOptionPane.showMessageDialog(this, "Greska! Pokusajte kasnije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
            Logger.getLogger(PregledFudbaleraForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        osvjeziPolja();
        pretrazeniFudbaleri = new ArrayList<>();
    }//GEN-LAST:event_jButtonPretraziOsvjeziActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmjeni;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonPretraziOsvjezi;
    private javax.swing.JComboBox<TreningGrupa> jComboBoxTreningGrupa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFudbaleri;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldJmbg;
    // End of variables declaration//GEN-END:variables

    public void popuniTabeluFudbaler() throws Exception {

        modelTabeleFudbaler = new ModelTabeleFudbalerTG();
        jTableFudbaleri.setModel(modelTabeleFudbaler);
    }

    private String validiraj(String ime, String jmbg) {
        String validan = "";
        if ((!ime.equals(""))) {

            if (!ime.matches("[a-zA-Z]+")) {
                validan += "Ime | ";
            }
        }
        if ((!jmbg.equals(""))) {

            if (!jmbg.matches("\\d+")) {
                validan += "JMBG | ";
            }
        }

        return validan;
    }

    private void osvjeziTabeluPretraga() {
        modelTabeleFudbaler = new ModelTabeleFudbalerTG(pretrazeniFudbaleri);
        jTableFudbaleri.setModel(modelTabeleFudbaler);
    }

    private void popuniComboTreningGrupa() throws Exception {
        listaTreningGrupa = Klijent.getInstance().ucitajListuTreningGrupe();
        for (TreningGrupa tg : listaTreningGrupa) {
            jComboBoxTreningGrupa.addItem(tg);
        }
        jComboBoxTreningGrupa.setSelectedIndex(-1);

    }

    private void osvjeziPolja() {
        jTextFieldIme.setText("");
        jTextFieldJmbg.setText("");
        jComboBoxTreningGrupa.setSelectedIndex(-1);
    }

    private boolean validirajPrazno(String ime, String jmbg, TreningGrupa tg) {
        if (ime.equals("") && jmbg.equals("") && tg.getObjID() == -1) {
            return true;
        }
        return false;
    }
}
