/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.ai.skolafudbala.forme;

import java.io.IOException;
import rs.ac.bg.fon.ai.skolafudbala.klijent.Klijent;
import rs.ac.bg.fon.ai.skolafudbala.model.Trener;
import rs.ac.bg.fon.ai.skolafudbala.modelitabele.ModelTabeleTrener;
import rs.ac.bg.fon.ai.skolafudbala.nacinprikazaforme.Prikaz;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;



/**
 *
 * @author Korisnik
 */
public class PregledTreneraForma extends javax.swing.JFrame {

    List<Trener> pretrazeniTreneri = new ArrayList<>();
    Trener trener;
    ModelTabeleTrener modelTabeleTrener;

    /**
     * Creates new form PregledTreneraForma
     */
    public PregledTreneraForma() {
        initComponents();
        this.setTitle("Informacije o postojećim trenerima");
        try {
            popuniTabeluTreneri();
        } catch (Exception ex) {
            if (ex instanceof IOException) {
                JOptionPane.showMessageDialog(this, "Greska! Pokusajte kasnije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTrener = new javax.swing.JTable();
        jButtonIzmjeni = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonPretrazi = new javax.swing.JButton();
        jTextFieldJMBG = new javax.swing.JTextField();
        jTextFieldIme = new javax.swing.JTextField();
        jButtonOsvjezi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Treneri");
        jLabel1.setMinimumSize(new java.awt.Dimension(60, 60));

        jTableTrener.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableTrener);

        jButtonIzmjeni.setText("Izmjeni");
        jButtonIzmjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmjeniActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("Obriši");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jLabel2.setText("Ime:");

        jLabel3.setText("JMBG:");

        jButtonPretrazi.setText("Pretraži");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jButtonOsvjezi.setText("Osvježi");
        jButtonOsvjezi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOsvjeziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButtonIzmjeni, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(179, 179, 179)
                            .addComponent(jButtonOsvjezi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jButtonPretrazi)
                    .addComponent(jTextFieldJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIzmjeni)
                    .addComponent(jButtonObrisi)
                    .addComponent(jButtonOsvjezi))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        try {
            String ime = jTextFieldIme.getText();
            String jmbg = jTextFieldJMBG.getText();
            boolean prazno = validirajPrazno(ime, jmbg);
            String validan = validiraj(ime, jmbg);
            if (!prazno) {
                if (validan.equals("")) {
                    Trener trenerPretraga = new Trener(ime, null, jmbg, -1);
                    pretrazeniTreneri = Klijent.getInstance().nadjiTrenere(trenerPretraga);
                    if (pretrazeniTreneri.size() == 1) {
                        JOptionPane.showMessageDialog(this, "Sistem je pronašao trenera po zadatim vrijednostima!", "Pretraga", JOptionPane.INFORMATION_MESSAGE);
                        osvjeziPolja();
                    } else {
                        JOptionPane.showMessageDialog(this, "Sistem je pronašao trenere po zadatim vrijednostima!", "Pretraga", JOptionPane.INFORMATION_MESSAGE);
                    }
                    osvjeziTabeluPretraga();
                } else {
                    JOptionPane.showMessageDialog(this, "Neispravan format: " + validan, "GRESKA", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Morate da unesete bar jedno polje da biste izvršili pretragu!", "GRESKA", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            if (ex instanceof IOException) {
                JOptionPane.showMessageDialog(this, "Greska! Pokusajte kasnije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            } else {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
                if (pretrazeniTreneri.size() > 0) {
                    modelTabeleTrener = new ModelTabeleTrener(pretrazeniTreneri);
                    jTableTrener.setModel(modelTabeleTrener);
                }
                try {
                    modelTabeleTrener = new ModelTabeleTrener();
                } catch (Exception ex1) {
                    if (ex instanceof IOException) {
                        JOptionPane.showMessageDialog(this, "Greska! Pokusajte kasnije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                        System.exit(0);
                    }
                }
                jTableTrener.setModel(modelTabeleTrener);
                osvjeziPolja();
            }
        }
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonIzmjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmjeniActionPerformed
        if (jTableTrener.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita trenera! Morate selektovati bar jednog trenera!", "GRESKA", JOptionPane.ERROR_MESSAGE);
        } else {

            trener = modelTabeleTrener.get(jTableTrener.getSelectedRow());
            Trener trenerBaza = new Trener();
            try {
                trenerBaza = Klijent.getInstance().ucitajTrenera(trener);
            } catch (Exception ex) {
                if (ex instanceof IOException) {
                    JOptionPane.showMessageDialog(this, "Greska! Pokusajte kasnije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                } else {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "GREŠKA", JOptionPane.ERROR_MESSAGE);
                }
            }
            UnosIzmjenaTreneraForma utf = new UnosIzmjenaTreneraForma(this, Prikaz.IZMJENI_FORMA, trenerBaza);
            utf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            JOptionPane.showMessageDialog(this, "Sistem je učitao trenera!", "Trener učitan", JOptionPane.INFORMATION_MESSAGE);
            utf.setVisible(true);
        }


    }//GEN-LAST:event_jButtonIzmjeniActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        if (jTableTrener.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita trenera! Morate selektovati bar jednog trenera!", "GRESKA", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                trener = modelTabeleTrener.get(jTableTrener.getSelectedRow());
                Trener trenerBaza = Klijent.getInstance().ucitajTrenera(trener);
                UnosIzmjenaTreneraForma utf = new UnosIzmjenaTreneraForma(this, Prikaz.OBRISI_FORMA, trenerBaza);
                utf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                JOptionPane.showMessageDialog(this, "Sistem je učitao trenera!", "Trener učitan", JOptionPane.INFORMATION_MESSAGE);
                utf.setVisible(true);
            } catch (Exception ex) {
                if (ex instanceof IOException) {
                    JOptionPane.showMessageDialog(this, "Greska! Pokusajte kasnije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                } else {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonOsvjeziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOsvjeziActionPerformed
        try {
            popuniTabeluTreneri();
        } catch (Exception ex) {
            if (ex instanceof IOException) {
                JOptionPane.showMessageDialog(this, "Greska! Pokusajte kasnije!", "GREŠKA", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }
        }
        osvjeziPolja();
        pretrazeniTreneri = new ArrayList<>();
    }//GEN-LAST:event_jButtonOsvjeziActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmjeni;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonOsvjezi;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTrener;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldJMBG;
    // End of variables declaration//GEN-END:variables

    private void popuniTabeluTreneri() throws Exception {
        modelTabeleTrener = new ModelTabeleTrener();
        jTableTrener.setModel(modelTabeleTrener);
    }

    public void osvjeziTabelu() throws Exception {
        popuniTabeluTreneri();
    }

    private void osvjeziTabeluPretraga() {
        modelTabeleTrener = new ModelTabeleTrener(pretrazeniTreneri);
        jTableTrener.setModel(modelTabeleTrener);
    }

    private String validiraj(String ime, String jmbg) {
        String validan = "";
        if ((!ime.equals(""))) {

            if (!ime.matches("[a-zA-Z]+")) {
                validan += "Ime | ";
            }
        }
        if ((!jmbg.equals(""))) {

            if (!jmbg.matches("\\d+")) {
                validan += "JMBG | ";
            }
        }

        return validan;
    }

    private void osvjeziPolja() {
        jTextFieldIme.setText("");
        jTextFieldJMBG.setText("");
    }

    private boolean validirajPrazno(String ime, String jmbg) {
        if (ime.equals("") && jmbg.equals("")) {
            return true;
        } else {
            return false;
        }
    }
}
