/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.ai.skolafudbala.formeServer;

import javax.swing.JFrame;



/**
 *
 * @author Korisnik
 */
public class MainFormaServer extends javax.swing.JFrame {

    /**
     * Creates new form MainForma
     */
    public MainFormaServer() {
        initComponents();
        this.setTitle("Škola fudbala");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuServer = new javax.swing.JMenu();
        jMenuKonfig = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dobro došli! Molim odaberite opciju iz glavnog menija");

        jMenuServer.setText("Server");
        jMenuServer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuServerMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuServer);

        jMenuKonfig.setText("Konfiguracija baze podataka");
        jMenuKonfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuKonfigMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuKonfig);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuServerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuServerMouseClicked
        ServerForma sf = new ServerForma();
        sf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        sf.setVisible(true);
    }//GEN-LAST:event_jMenuServerMouseClicked

    private void jMenuKonfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuKonfigMouseClicked
        KonfiguracijaBazeForma kbf = new KonfiguracijaBazeForma();
        kbf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        kbf.setVisible(true);
    }//GEN-LAST:event_jMenuKonfigMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuKonfig;
    private javax.swing.JMenu jMenuServer;
    // End of variables declaration//GEN-END:variables
}
